# Generated by Django 5.0.6 on 2024-06-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0009_nationality_remove_teacherworkload_classl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=20)),
                ('shift', models.IntegerField()),
                ('class_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.classgroup')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.classroom')),
                ('classroom2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_g22', to='admin_app.classroom')),
                ('ring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.ring')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.school')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.subject')),
                ('subject2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_g22', to='admin_app.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.teacher')),
                ('teacher2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_g22', to='admin_app.teacher')),
                ('typez', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.extra_lessons')),
            ],
        ),
    ]
