version: '3.8'

services:
#  db:
#    image: postgres:15-alpine
#    container_name: db
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: mydatabase
#    volumes:
#      - db_data:/var/lib/postgresql/data
#    networks:
#      - net


  redis:
   image: redis
   restart: always
   ports:
     - "6379:6379"
   networks:
     - net

  webapp:
   build:
     context: .
     dockerfile: Dockerfile
   depends_on:
#     - db
     - redis
   networks:
     - net
   ports:
     - '8001:8001'
   volumes:
     - .:/code
     - static_volume:/code/static


  worker:
   restart: always
   build:
     context: .
     dockerfile: ./celery/Dockerfile
   command: celery -A kestesikz worker -l info
   volumes:
     - ./:/code
   depends_on:
     - webapp
     - redis
#    entrypoint: ["/bin/sh", "-c"]

   networks:
     - net

  beat:
   restart: always
   build:
     context: .
     dockerfile: ./celery/Dockerfile
   command: celery -A kestesikz beat -l info
   volumes:
     - ./:/code
   networks:
      - net

   depends_on:
     - webapp
     - redis
     - worker
#    entrypoint: ["/bin/sh", "-c"]


networks:
  net:

volumes:
  postgres-data:
  static_volume:
  db_data: