# Generated by Django 4.2.7 on 2024-03-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher')], max_length=10, null=True),
        ),
    ]
