# Generated by Django 4.2.7 on 2024-01-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_news_qr_code'),
        ('auth_user', '0002_user_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_user', to='admin_app.school'),
        ),
    ]
