# Generated by Django 4.2.7 on 2024-02-20 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoforNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='photos1',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AddField(
            model_name='photofornews',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_photos', to='admin_app.news'),
        ),
        migrations.AddField(
            model_name='news',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='news_photos', to='admin_app.photofornews'),
        ),
    ]
