# Generated by Django 4.2.7 on 2024-02-29 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='food_reti',
        ),
        migrations.RemoveField(
            model_name='school',
            name='city',
        ),
        migrations.AddField(
            model_name='schoolpasport',
            name='school_name',
            field=models.CharField(blank=True, max_length=355, null=True),
        ),
        migrations.AlterField(
            model_name='altynbelgi',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='altynbelgi',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='classrooms',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='classl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.class'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.classrooms'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='classroom2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom2', to='admin_app.classrooms'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='ring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.dopurokring'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.subject'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject2', to='admin_app.subject'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.teacher'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher2', to='admin_app.teacher'),
        ),
        migrations.AlterField(
            model_name='dopurok',
            name='typez',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.extra_lessons'),
        ),
        migrations.AlterField(
            model_name='dopurokring',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='extra_lessons',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='end_date',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='job_characteristic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='start_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kruzhok',
            name='kruzhok_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='kruzhok',
            name='purpose',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kruzhok',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='kruzhok',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.teacher'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='kruzhok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='admin_app.kruzhok'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='start_end_time',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='week_day',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='news',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='oner_success',
            name='classl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='oner_success',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='oner_success',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='oner_success',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='oner_success',
            name='student_success',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pandikolimpiada_success',
            name='classl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pandikolimpiada_success',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pandikolimpiada_success',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pandikolimpiada_success',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='pandikolimpiada_success',
            name='student_success',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redcertificate',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='redcertificate',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='ring',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.class'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.classrooms'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='classroom2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom_g2', to='admin_app.classrooms'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.ring'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_g2', to='admin_app.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.teacher'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_g2', to='admin_app.teacher'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='typez',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.extra_lessons'),
        ),
        migrations.AlterField(
            model_name='school',
            name='region',
            field=models.CharField(blank=True, choices=[('almaty', 'almaty'), ('astana', 'astana'), ('shymkent', 'shymkent'), ('abay_oblast', 'abay_oblast'), ('akmolinsk_oblast', 'akmolinsk_oblast'), ('aktobe_oblast', 'aktobe_oblast'), ('almaty_region', 'almaty_region'), ('atyrau_oblast', 'atyrau_oblast'), ('east_kazakhstan_oblast', 'east_kazakhstan_oblast'), ('zhambyl_oblast', 'zhambyl_oblast'), ('zhetysu_oblast', 'zhetysu_oblast'), ('west_kazakhstan_oblast', 'west_kazakhstan_oblast'), ('karaganda_oblast', 'karaganda_oblast'), ('kostanay_oblast', 'kostanay_oblast'), ('kyzylorda_oblast', 'kyzylorda_oblast'), ('mangystau_oblast', 'mangystau_oblast'), ('pavlodar_oblast', 'pavlodar_oblast'), ('north_kazakhstan_oblast', 'north_kazakhstan_oblast'), ('turkestan_oblast', 'turkestan_oblast'), ('ulytau_oblast', 'ulytau_oblast')], max_length=255, null=True, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='school',
            name='timezone',
            field=models.CharField(choices=[('GMT+5', 'GMT+5'), ('GMT+6', 'GMT+6')], default='GMT+5', max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='school_administration',
            name='administator_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='school_administration',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='school_director',
            name='director_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='school_director',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='school_socialmedia',
            name='account_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='school_socialmedia',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='schoolmap',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='all_pedagog_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='amount_of_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='amount_of_family',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='amount_of_parents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='dayarlyk_class_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='dayarlyk_student_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='established',
            field=models.IntegerField(blank=True, default=2008, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='kiz_sany',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='number_of_10_11_classes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='number_of_10_11_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='number_of_1_4_classes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='number_of_1_4_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='number_of_5_9_classes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='number_of_5_9_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='number_of_classes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='number_of_students',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog_1sanat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog_2sanat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog_moderator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog_sanat_zhok',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog_sarapshy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog_sheber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog_stazher',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog_zertteushy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='pedagog_zhogary',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='school_address',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='school_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='school_lang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='ul_sany',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolpasport',
            name='vmestimost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='specialityhistory',
            name='degree',
            field=models.CharField(blank=True, choices=[('bakalavr', 'bakalavr'), ('magistratura', 'magistratura'), ('doktorantura', 'doktorantura'), ('srednee', 'srednee'), ('viswee', 'viswee')], default='bakalavr', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='specialityhistory',
            name='end_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specialityhistory',
            name='mamandygy',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='specialityhistory',
            name='speciality_university',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sport_success',
            name='classl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sport_success',
            name='fullname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='sport_success',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sport_success',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='sport_success',
            name='student_success',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='classl',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.class'),
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.classrooms'),
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.subject'),
        ),
        migrations.AlterField(
            model_name='teacherworkload',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.teacher'),
        ),
    ]
