# Generated by Django 4.2.7 on 2024-04-08 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSchoolPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='school_photos/')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school')),
            ],
            options={
                'verbose_name_plural': 'MainSchoolPhoto',
            },
        ),
    ]
