# Generated by Django 4.2.7 on 2024-01-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='region',
            field=models.CharField(choices=[('abay', 'Абайская область'), ('akmolinsk', 'Акмолинская область'), ('aktobe', 'Актюбинская область'), ('almaty_region', 'Алматинская область'), ('atyrau', 'Атырауская область'), ('east_kazakhstan', 'Восточно-Казахстанская область'), ('zhambyl', 'Жамбылская область'), ('zhetysu', 'Жетысуская область'), ('west_kazakhstan', 'Западно-Казахстанская область'), ('karaganda', 'Карагандинская область'), ('kostanay', 'Костанайская область'), ('kyzylorda', 'Кызылординская область'), ('mangystau', 'Мангистауская область'), ('pavlodar', 'Павлодарская область'), ('north_kazakhstan', 'Северо-Казахстанская область'), ('turkestan', 'Туркестанская область'), ('ulytau', 'Улытауская область')], max_length=255, null=True, verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(choices=[('almaty', 'Алматы'), ('astana', 'Астана'), ('shymkent', 'Шымкент')], default='almaty', max_length=255, null=True, verbose_name='city'),
        ),
    ]
