# Generated by Django 4.2.7 on 2024-03-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpasport',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
