# Generated by Django 4.2.7 on 2024-03-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_alter_schoolpasport_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_socialmedia',
            name='type',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('Youtube', 'Youtube'), ('Website', 'Website'), ('Tgbot', 'Tgbot')], default='Youtube', max_length=10),
        ),
    ]
