# Generated by Django 4.2.7 on 2024-04-08 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_mainschoolphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainschoolphoto',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to='admin_app.school'),
        ),
    ]
