# Generated by Django 4.2.7 on 2024-02-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_remove_menu_food_reti_remove_school_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmap',
            name='flat1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='schoolmap',
            name='map',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
