# Generated by Django 4.2.7 on 2024-01-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_school_region_alter_school_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
