# Generated by Django 4.2.7 on 2024-02-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_remove_news_photos_news_img1_news_img10_news_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img10',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img4',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img5',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img6',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img7',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img8',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='img9',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
