# Generated by Django 4.2.7 on 2024-04-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_mainschoolphoto_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainschoolphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo10',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo7',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo8',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
        migrations.AddField(
            model_name='mainschoolphoto',
            name='photo9',
            field=models.ImageField(blank=True, null=True, upload_to='school_photos/'),
        ),
    ]
