# Generated by Django 4.2.7 on 2024-03-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_alter_schoolmap_flat1_alter_schoolmap_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_letter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
