# Generated by Django 4.2.7 on 2024-04-08 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_remove_mainschoolphoto_photo_mainschoolphoto_photo1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=255)),
                ('y', models.CharField(max_length=255)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_coordinates', to='admin_app.school')),
            ],
            options={
                'verbose_name_plural': 'MapCoordinates',
            },
        ),
    ]
