# Generated by Django 4.2.7 on 2024-05-16 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_mapcoordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.CreateModel(
            name='ProudOfSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('student_success', models.TextField(blank=True, null=True)),
                ('success', models.CharField(blank=True, choices=[('sport', 'sport'), ('olimpiada', 'olimpiada'), ('altynbelgi', 'altynbelgi'), ('redcertificate', 'redcertificate')], default='olimpiada', max_length=200, null=True)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school')),
            ],
            options={
                'verbose_name_plural': 'Pride of the School',
            },
        ),
    ]
