# Generated by Django 4.2.7 on 2024-01-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_alter_news_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_socialmedia',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='social_media_qrcodes/'),
        ),
    ]
