# Generated by Django 4.2.7 on 2024-02-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_school_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialityhistory',
            name='mamandygy',
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='end_date',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='jobhistory',
            name='start_date',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='specialityhistory',
            name='degree',
            field=models.CharField(choices=[('bakalavr', 'Бакалавр'), ('magistratura', 'Магистратура'), ('doktorantura', 'Докторантура'), ('srednee', 'Cреднее'), ('viswee', 'Высшее')], default='bakalavr', max_length=200),
        ),
        migrations.AlterField(
            model_name='specialityhistory',
            name='end_date',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='subject',
            name='type',
            field=models.CharField(blank=True, choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pedagog',
            field=models.CharField(blank=True, choices=[('pedagog_sheber', 'Pedagog Sheber'), ('pedagog_zertteushy', 'Pedagog  Zertteushy'), ('pedagog_sarapshy', 'Pedagog Sarapshy'), ('pedagog_moderator', 'Pedagog Moderator'), ('pedagog', 'Pedagog'), ('pedagog_stazher', 'Pedagog  Stazher'), ('pedagog_zhogary', 'Pedagog  Zhogary'), ('pedagog1sanat', 'Pedagog  1 sanat'), ('pedagog2sanat', 'Западно-Казахстанская область'), ('pedagog_sanat_zhok', 'Карагандинская область')], default='pedagog', max_length=200, null=True),
        ),
    ]
