# Generated by Django 4.2.7 on 2024-01-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_school_socialmedia_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='news_qrcodes/'),
        ),
    ]
