# Generated by Django 4.2.7 on 2024-05-21 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_school_qrcode_proudofschool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolpasport',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_app.school'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolpasport',
            unique_together={('school',)},
        ),
    ]
