# Generated by Django 4.2.7 on 2024-01-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_alter_news_qr_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school_socialmedia',
            unique_together={('school', 'type')},
        ),
    ]
