# Generated by Django 4.2.7 on 2024-02-21 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_remove_specialityhistory_mamandygy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.classrooms'),
        ),
        migrations.AlterField(
            model_name='class',
            name='language',
            field=models.CharField(blank=True, choices=[('KZ', 'KZ'), ('RU', 'RU')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pedagog',
            field=models.CharField(blank=True, choices=[('pedagog_sheber', 'Pedagog Sheber'), ('pedagog_zertteushy', 'Pedagog  Zertteushy'), ('pedagog_sarapshy', 'Pedagog Sarapshy'), ('pedagog_moderator', 'Pedagog Moderator'), ('pedagog', 'Pedagog'), ('pedagog_stazher', 'Pedagog  Stazher'), ('pedagog_zhogary', 'Pedagog  Zhogary'), ('pedagog1sanat', 'Pedagog  1 sanat'), ('pedagog2sanat', 'Pedagog  2 sanat'), ('pedagog_sanat_zhok', 'Pedagog sanat zhok')], default='pedagog', max_length=200, null=True),
        ),
    ]
