# Generated by Django 5.0.6 on 2024-06-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0009_nationality_remove_teacherworkload_classl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classgroup',
            old_name='nationality',
            new_name='language',
        ),
    ]
