# Generated by Django 5.0.6 on 2024-06-12 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_rename_nationality_classgroup_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubject',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.classroom'),
        ),
    ]
