# Generated by Django 4.2.7 on 2024-02-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0011_alter_news_date_alter_news_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialityhistory',
            name='mamandygy',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
