# Generated by Django 5.0.6 on 2024-06-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0012_remove_menu_food_reti_school_school_map_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolpasport',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='altynbelgi',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='extra_lessons',
            name='type_color',
        ),
        migrations.RemoveField(
            model_name='oner_success',
            name='classl',
        ),
        migrations.RemoveField(
            model_name='pandikolimpiada_success',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='redcertificate',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='school_administration',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='sport_success',
            name='class_group',
        ),
        migrations.AlterField(
            model_name='altynbelgi',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='kruzhok',
            name='purpose',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='redcertificate',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='school_administration',
            name='administator_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='school_director',
            name='director_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
