# Generated by Django 4.2.7 on 2024-04-05 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('value', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
                ('class_hours', models.ManyToManyField(related_name='week_days', to='admin_app.ring')),
            ],
            options={
                'verbose_name_plural': 'WeekDays',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subgroup', models.BooleanField(default=False)),
                ('total_load', models.PositiveIntegerField(default=1)),
                ('lessons_per_week', models.PositiveIntegerField(default=1)),
                ('double_lesson', models.BooleanField(default=False)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_school', to='admin_app.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='admin_app.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='admin_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='admin_app.teacher')),
            ],
            options={
                'verbose_name_plural': 'Schedules',
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='admin_app.ring')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='autogenerate.schedule')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classSubject_school', to='admin_app.school')),
                ('week_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='autogenerate.weekday')),
            ],
            options={
                'verbose_name_plural': 'ClassSubjects',
            },
        ),
    ]
