# Generated by Django 4.2.7 on 2024-04-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autogenerate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsubject',
            name='class_room',
        ),
        migrations.DeleteModel(
            name='ClassRoom',
        ),
    ]
