# Generated by Django 4.2.7 on 2024-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_mapcoordinates'),
        ('autogenerate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekday',
            name='class_hours',
            field=models.ManyToManyField(blank=True, null=True, related_name='week_days', to='admin_app.ring'),
        ),
    ]
