# Generated by Django 4.2.7 on 2024-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autogenerate', '0004_alter_weekday_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='double_lesson',
            field=models.BooleanField(default=False),
        ),
    ]
