# Generated by Django 5.0.6 on 2024-06-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0009_nationality_remove_teacherworkload_classl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField()),
                ('caption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('post_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.school')),
            ],
        ),
    ]
